### ISSUE TITLE
Tweaks gone after rebooting and using Checkra1n again

### ISSUE THREAD

**Issue by termz64** [checkra1n/BugTracker#121]
**What device + iOS version are you on?**
iPhone 8+ (10,2) 13.2.2

**What checkra1n version are you using?**
0.9.1
**What are the steps to reproduce the issue?**
1.Install any tweak(s)
2.Reboot
3.Re-jailbreak with checkra1n
4.All tweaks are gone, but sources are all there
...

**What do you expect, and what is happening instead?**
Tweaks to be loaded

**Any other info, error logs, screenshots, ...?**
Just installed like 20 tweaks and after rebooting and rejailbreaking the tweaks are all gone. Also the option to reinstall cydia crashes when pressed in the checkra1n app. I can't imagine any of this is normal, I sure as hell hope not

**Comment by mrichardist** [comment]
Have you tried updating preferenceloader?

**Comment by termz64** [comment]
Yes

**Comment by abrvham** [comment]
Iphone 10.6 iOS 13.2.2
Same for me here, PreferenceLoader installed

**Comment by abrvham** [comment]
To mitigate this issue, I've made a complete phone reset (using DFU mode), and then used an iCloud backup. Now Cydia and tweaks works after a second jailbreak.
More device info:
- Used unc0ver previoulsy on iOS 12.4 (v3.7 probably)
- Sileo via Undecimus was installed, Cydia deleted (on previous jailbreak)
- restored RootFS before using checkra1n

It seems that it's not an isolated case as some people on Reddit have this issue.

**Comment by james5294** [comment]
Exactly the same for me

iPhone X 13.2.2

**Comment by james5294** [comment]
> To mitigate this issue, I've made a complete phone reset (using DFU mode), and then used an iCloud backup. Now Cydia and tweaks works after a second jailbreak.
> More device info:
> 
> * Used unc0ver previoulsy on iOS 12.4 (v3.7 probably)
> * Sileo via Undecimus was installed, Cydia deleted (on previous jailbreak)
> * restored RootFS before using checkra1n
> 
> It seems that it's not an isolated case as some people on Reddit have this issue.

 This is the same way I fixed it. Complete restore of phone then iCloud backup tested twice works fine. 

Hope this helps the next person..

**Comment by termz64** [comment]
> > To mitigate this issue, I've made a complete phone reset (using DFU mode), and then used an iCloud backup. Now Cydia and tweaks works after a second jailbreak.
> > More device info:
> > 
> > * Used unc0ver previoulsy on iOS 12.4 (v3.7 probably)
> > * Sileo via Undecimus was installed, Cydia deleted (on previous jailbreak)
> > * restored RootFS before using checkra1n
> > 
> > It seems that it's not an isolated case as some people on Reddit have this issue.
> 
> This is the same way I fixed it. Complete restore of phone then iCloud backup tested twice works fine.
> 
> Hope this helps the next person..

When was the backup from? Before or after using unc0ver?

**Comment by termz64** [comment]
I can confirm as well that this works. Thanks

**Comment by james5294** [comment]
My back up was the most recent backed up. In theory it shouldn’t of made a difference. But it did. LOL  at least it worked.

**Comment by abdelle7** [comment]
same here , I've made a complete phone reset (DFU) but the problem still persist.
what should i do ?? 
i'm using iPhone 7, iOS 13.2.3, with checkra1n 0.9.5 beta

**Comment by abdelle7** [comment]
> same here , I've made a complete phone reset (DFU) but the problem still persist.
> what should i do ??
> i'm using iPhone 7, iOS 13.2.3, with checkra1n 0.9.5 beta

i install **PreferenceLoader** and now all works great, thanks
