### ISSUE TITLE
tvOS 14.0 "check_snapshot_error_code" when jailbreaking

### ISSUE THREAD

**Issue by CodeyMoore** [checkra1n/BugTracker#1684]
**Tell us about your setup:**
1. What iDevice are you using?
Apple TV HD

2. On what version of iOS is it?
tvOS 14.0

3. What version of checkra1n are you using?
latest 0.11.0 release

4. What is your host system (OS version? Hackintosh? VM? etc.)?
MBP mid 2012 running macOS Catalina 10.15.6

5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A to USB-C. No USB hub

**What are the steps to reproduce the issue?**
1. Open checkra1n and put Apple TV into DFU mode
2. Jailbreak
3. Installer runs on screen
4. "Check_snapshot_error_code" text appears with "exit" button under near text

**What do you expect, and what is happening instead?**
Expected to be jailbroken, instead received an error

**Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
normal and safemode

**Any other info, error logs, screenshots, ...?**
![IMG_8840](https://user-images.githubusercontent.com/21144094/93848524-f7e7d780-fce8-11ea-9c81-1641f941e14e.jpg)

**Comment by Anonymous341** [comment]
Got the same error code on Apple TV HD on 14.0 too and the same setup. Any idea how to resolve it?

**Comment by CodeyMoore** [comment]
> Got the same error code on Apple TV HD on 14.0 too and the same setup. Any idea how to resolve it?

I've wiped my Apple TV on the odd chance that it could maybe help but it didnt :(

**Comment by Anonymous341** [comment]
> > Got the same error code on Apple TV HD on 14.0 too and the same setup. Any idea how to resolve it?
> 
> I've wiped my Apple TV on the odd chance that it could maybe help but it didnt :(

Same here man. I wiped my ATV from 12.4 as nitoTV stopped working. Now its worse 🤪🙃

**Comment by CodeyMoore** [comment]
> Got the same error code on Apple TV HD on 14.0 too and the same setup. Any idea how to resolve it?

I've wiped my Apple TV on the odd chance that it could maybe help but it didnt :(

**Comment by CodeyMoore** [comment]
> > > Got the same error code on Apple TV HD on 14.0 too and the same setup. Any idea how to resolve it?
> > 
> > 
> > I've wiped my Apple TV on the odd chance that it could maybe help but it didnt :(
> 
> Same here man. I wiped my ATV from 12.4 as nitoTV stopped working. Now its worse 🤪🙃

I Just downgraded to tvOS 13.4.8 and I'm having a similar issue. I can jailbreak but it doesnt load the installer :/

Edit: using checkra1n version 0.10.2 solved the tvOS 13.4.8

**Comment by noppefoxwolf** [comment]
I'm getting same issue on 0.11.0.
Using tvos14 in appleTV 4gen.
factory reseted too.

**Comment by Gottesbrau** [comment]
Same

**Comment by muhammadali1f** [comment]
Same here recieving same error
tvOS 14 
Checkra1n v11.0
Kali Linux
original apple USB C cable

**Comment by rewoikon** [comment]
Same
![check_snapshot_error_code](https://user-images.githubusercontent.com/68848401/94024172-c2fa8400-fdbf-11ea-832b-99907873825b.JPG)
![F4B3E06D-AD49-48B3-AC9B-93042FB5F3D3](https://user-images.githubusercontent.com/68848401/94024176-c42bb100-fdbf-11ea-9d62-fcbf18d89120.JPG)

**Comment by Tobicake** [comment]
This seems to happen to everyone. Same here.

tvOS 14
Apple TV 5,3 (Apple TV 4th Gen)
checkra1n beta 0.11.0

**Comment by noppefoxwolf** [comment]
Is anyone successful?

**Comment by mycastlex** [comment]
Same here. 

tvOS 14
Apple TV 5,3 (Apple TV 4th Gen)
checkra1n beta 0.11.0

**Comment by dougmcarthur** [comment]
I wonder if anyone has successfully jailbroken on tvOS 14? I just tried on 14.0.1 using checkra1n beta 0.11.0 and got the same result. :/

**Comment by timemaster5** [comment]
Same here, tested on tvos 14 and 14.0.1

**Comment by Mysticales** [comment]
Same issue here, Installed fine using Ubuntu, but on 14.0.1 it gets stuck on that check snapshot..

Btw is it possible, even after a DFU that some jb files or fs from what was it greenpoison? Was left here messing it up?

**Comment by bosu1787** [comment]
same here on 14.0.1 using raspberry pi 4, installed fine but get check_snapshot_error_code......

**Comment by Mysticales** [comment]
Anyone try the tvos beta profile to prevent ota download? And speaking of ota. Anyone know where the ota file is stored on tvos? Cause could be there is something there and its not being purged on the jailbreak like other ios devices are.

**Comment by assiri888** [comment]
> Got the same error code on Apple TV HD on 14.0 too and the same setup. Any idea how to resolve it?

**Comment by assiri888** [comment]
> **Tell us about your setup:**
> 
> 1. What iDevice are you using?
> 
> Apple TV HD
> 
> 
> 
> 2. On what version of iOS is it?
> 
> tvOS 14.0
> 
> 
> 
> 3. What version of checkra1n are you using?
> 
> latest 0.11.0 release
> 
> 
> 
> 4. What is your host system (OS version? Hackintosh? VM? etc.)?
> 
> MBP mid 2012 running macOS Catalina 10.15.6
> 
> 
> 
> 5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
> 
> USB-A to USB-C. No USB hub
> 
> 
> 
> **What are the steps to reproduce the issue?**
> 
> 1. Open checkra1n and put Apple TV into DFU mode
> 
> 2. Jailbreak
> 
> 3. Installer runs on screen
> 
> 4. "Check_snapshot_error_code" text appears with "exit" button under near text
> 
> 
> 
> **What do you expect, and what is happening instead?**
> 
> Expected to be jailbroken, instead received an error
> 
> 
> 
> **Does the issue also occur if you tick "Safe Mode" in the checkra1n options?**
> 
> normal and safemode
> 
> 
> 
> **Any other info, error logs, screenshots, ...?**
> 
> ![IMG_8840](https://user-images.githubusercontent.com/21144094/93848524-f7e7d780-fce8-11ea-9c81-1641f941e14e.jpg)
> 
>

**Comment by cs59** [comment]
Getting same issue here

**Comment by MDausch** [comment]
I’ve tried it on 14.0, 14.0.1, and 14.0.2 and get the same error

**Comment by timemaster5** [comment]
It seems to me like nobody can use checkra1n on tvOS 14. I know there is a lot of other work, but this looks like the originally introduced functionality doesn't work at all. So I think it should be either removed from the list of features on the official page (https://checkra.in/releases/), which would prevent more people from reporting this as a bug, or fixed with some priority. As it is probably a result of some small mistake/typo, to comply with the original statement.

**Comment by PancakeSparkle** [comment]
Also not working with checkra1n 0.12 on tvOS 14.2, same error

**Comment by getafe83** [comment]
Not working on tvos 14.2 and checkra1n 0.12

**Comment by timemaster5** [comment]
Same for me :( I tried the Mac GUI version, and also Linux CLI, but the result is the same every time. I have just also tried to restore the factory defaults, to be safe.. no difference :(

**Comment by totosossa** [comment]
Error, snapshot.....tvOs 14.2, checkra1n 0.12.0,  Linux mint

**Comment by yes67** [comment]
tvOS 14.0.2 checkra1n 0.12.0 same issue using checkn1x on a windows PC

**Comment by rubensrt8** [comment]
![Uploading 31742593-54B4-4A9B-8B7A-D67E45831CC2.jpeg…]()
 Same here 14.2

**Comment by kurazli** [comment]
Tell us about your setup:

What iDevice are you using?
Apple TV HD

On what version of iOS is it?
tvOS 14.0

What version of checkra1n are you using?
checkra1n 0.12.0 beta

What is your host system (OS version? Hackintosh? VM? etc.)?
MBA 2018 running macOS Catalina 10.15.7

How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-C to USB-C and USB-C to USB-A to USB-C. No USB hub

What are the steps to reproduce the issue?

Open checkra1n and put Apple TV into DFU mode
Jailbreak
Installer runs on screen
"Check_snapshot_error_code" text appears with "exit" button under near text
checkra1n loader app is available in the menu, but results in the same error.

What do you expect, and what is happening instead?
Expected to be jailbroken, instead received an error

Does the issue also occur if you tick "Safe Mode" in the checkra1n options?
normal and safemode

Any other info, error logs, screenshots, ...?

**Comment by noppefoxwolf** [comment]
I resolved on checkrain 0.12.1.
Thank you!!

**Comment by bosu1787** [comment]
Niceeeeeeeeeeeeeeeeeeeeeee !!!

thanks.

**Comment by cs59** [comment]
> I resolved on checkrain 0.12.1.
> Thank you!!

Really? this error ‘check_snapshot_error’ is solved in 0.12.1 checkra1n?

**Comment by Apple4Barres** [comment]
I have an Apple Tv 4k in 14.4, I use GoldenEye and DSDC cable with Checkra1n 0.12.2 and it gives me an error "check_snapshot_error". I have tried to use Checkra1n 0.12.1 but I can't get past "Booting" and it restarts. Any solution? I have another Apple TV 4K also in 14.4 and in that second device the error "check_snapshot_error" does not appear

**Comment by Apple4Barres** [comment]
Video --> https://twitter.com/apple4barres/status/1361007653040881668?s=21

**Comment by Apple4Barres** [comment]
![image0](https://user-images.githubusercontent.com/79045832/117535683-2e176480-aff7-11eb-9745-38e90b2a9b27.jpeg)

The problem persists, I have updated AppleTV4K to 14.4 and using checkra1n in "CLI" mode with goldenEYE + DCSD and always the same error "check_snapshot" I have tried more than 15 times in a row
