### ISSUE TITLE
Substrate crashing (kernel panics / tweaks stop working)

### ISSUE THREAD

**Issue by xorpix** [checkra1n/BugTracker#533]
1. What iDevice are you using?
iPhone 8 Plus
2. On what version of iOS is it?
iOS 13.2.3
3. What version of checkra1n are you using? GUI or CLI?
GUI 0.9.5
4. What is your host system (OS version? Hackintosh? VM? etc.)?
macOS 10.15.1
5. How are you connecting to the device (USB-A? USB-C? Apple/3rd party cable? Through a USB hub?)?
USB-A

**What are the steps to reproduce the issue?**
1. Just simply using the device
2. Suddenly everything begins to lag until the screen completely freezes 
3. After about 2 minutes it falls into something like ldrestart loop (dimmed respring wheel) and reboots in few minutes in unjailbroken state

**What do you expect, and what is happening instead?**

**Does the issue also occur if you enable Safe Mode?**

**Any other info, error logs, screenshots, ...?**
Here are panic logs:

https://we.tl/t-FbbkOvqwWw
https://we.tl/t-s2WeX36UgP

```

**Comment by Siguza** [comment]
Your logs show a lot of `xpcproxy` and some other processes in suspended state, which is certainly not standard behaviour. I'm fairly certain this is a tweak that is either restarting processes en masse, or hooking and stalling them on restart.  
The best advice I can give you is to use iCleaner to disable half of your tweaks, see if the bug still occurs, then disable half of those still enabled, etc. until you identify the one causing it. :/

**Comment by xorpix** [comment]
Thank You for your reply. Also, I will attach my tweak list here.

```
7-zip (POSIX): 16.02-1
AppList: 1.5.15~beta1
APT (apt-key): 1.8.2-1
APT (libapt-pkg): 1.8.2-1
APT 0.7 Transitional (apt-key): 1:0
APT 1.4 Transitional: 1:0
APT Strict (lib): 1.8.2-1
APT: 1.8.2-3
Assuan: 2.5.1-1
Base Structure: 1-5
Berkeley DB: 6.2.32-1
BetterCCXI: 1.6.0
BigBoss Icon Set: 1.0
Bourne-Again SHell: 5.0.3-2
bzip2: 1.0.6-1
CA Certs: 0.0.2
CCSupport: 1.2.2
Cephei: 1.13.1-2
Cercube for YouTube: 5.1.2
CopyLog: 1.2.6
Core Utilities (/bin): 8.31-1
Core Utilities: 8.31-1
Cydia Installer: 1.1.32~b23
Cydia Substrate: 0.9.7100~b3
Cydia Translations: 1.1.32~b1
Dark: 1.5
Darwin Tools: 1.1-1
Debian Packager: 1.19.7-1
Debian Utilities: 4.8.6-1
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
EmojiKey: 1.4
Essential: 0-1
FDots: 1.0.1
file: 5.35-2
Filza File Manager 64-bit: 3.7.3-16
Find Utilities: 4.6.0-2
Firefly: 2.0.1-1
Flame: 1.3
FoxFort Tools: 1.0.9
gettext: 0.19.8-1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
grep: 3.1-1
gzip: 1.9-1
iCleaner Pro: 7.7.5
iOS Firmware: 13.2.3
iPhone Firmware (/sbin): 0-1
Jellyfish: 1.3.3
Kal Theme Pack 2: 2.4
KSBA: 1.3.5-1
Launch Daemon Controller: 22-1
libcolorpicker: 1.6.6
libCSColorPicker: 1.0.3
libfoxfortutils: 1.0.11
libidn2: 6.1.2-1
libpackageinfo (cokepokes): 1.1.0.1-3
libplist: 2.0.0-2
libSparkAppList: 1.0.4
libswift (stable): 5.0
libtasn1: 4.13-1
libunistring: 0.9.10-1
Link Identity Editor: 2:2.1.2+24497ae-1
Locale Profiles in UTF-8: 1.0-1
LocalIAPStore: 1.4-2
Lotus Dark: 1.0.9
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
Magma Pro: 1.4.1
MDausch Utils: 0.0.4
Nettle: 3.4.1-1
New Curses: 5.9-1
New Curses: 6.1-1
New GNU Portable Threads: 1.6-1
NewTerm (iOS 10 – 13): 2.3
NoDNDBanner: 0.0.1
OpenSSH: 7.9p1-3
OpenSSL 1.0 Libraries: 1.0.2s-1
p11-kit: 0.23.12-1
PortraitXI: 1.0.5
powerlogHelperdFix: 1.0
PowerModule: 1.2.6
PreferenceLoader: 2.2.4~beta1
Profile Directory: 0-1
readline: 8.0-1
RocketBootstrap: 1.0.7~beta3
Safari Plus: 1.7.8-2
sed: 4.5-1
shell-cmds: 118-8
Snappy: 1.3.0
SnowBoard Settings Icons Extension: 1.0.17~Beta1
SnowBoard: 1.2.74~Beta1
Soda Repo Icons: 1.2
star vpn: 0.0.1-1+debug
Substrate Safe Mode: 0.9.6003
Switches: 2.1
Sylph: 1.3~Beta.1
System Info: 2.3.2-6+debug
system-cmds: 790.30.1-2
Tape Archive: 1.30-2
TechSupport Framework (cokepokes): 1.5.0.1-2
TFDidThatSay?: 1.2.7
UIKit Tools: 1.1.15-2
unrar: 5.6.4-1
unzip: 6.0+deb9u1-1
wget: 1.19.5-2
XZ Utils: 5.2.4-4
zip: 2.32-1
```

**Comment by foxfortmobile** [comment]
I have been having same issue. got 3 random freeze with exact behaviour as @xorpix mentioned. Here is my panic log:
https://pastebin.com/4Kc356QU

my tweak list:
```
7-zip (POSIX): 16.02-1
Aperturize: 1.1.0-45+debug
AppList: 1.5.15~beta1
APT (apt-key): 1.8.2-1
APT (libapt-pkg): 1.8.2-1
APT 0.7 Transitional (apt-key): 1:0
APT 1.4 Transitional: 1:0
APT Strict (lib): 1.8.2-1
APT: 1.8.2-3
Assuan: 2.5.1-1
Barmoji: 1.7
Base Structure: 1-5
Berkeley DB: 6.2.32-1
BigBoss Icon Set: 1.0
Bourne-Again SHell: 5.0.3-2
bzip2: 1.0.6-1
CA Certs: 0.0.2
CCModules: 1.4-3
CCSupport: 1.2.2
Cephei: 1.13.1-2
CocoaTop: 2.0.2
Core Utilities (/bin): 8.31-1
Core Utilities: 8.31-1
CrashReporter (SparkDev): 1.17.2
Cydia Installer: 1.1.32~b22
Cydia Substrate: 0.9.7100~b3
Cydia Translations: 1.1.32~b1
DarkSounds: 1.5.2-1+debug
Darwin Tools: 1.1-1
Debian Packager: 1.19.7-1
Debian Utilities: 4.8.6-1
Deluminator: 2.2.12-59+debug
Diff Utilities: 3.6-1
Dimage: 1.2.1-1+debug
diskdev-cmds: 593.221.1-1
Eclipse Dark Mode (iOS 12): 6.1.2-2
Essential: 0-1
FacebookDarkMode: 2.5.1-5+debug
file: 5.35-2
Filza File Manager 64-bit: 3.7.2-24
Find Utilities: 4.6.0-2
Flame: 1.3
Flex 3: 3~EarlyAccess4
FLEXing: 0.0.12-4
FoxFort Tools: 1.0.9
gettext: 0.19.8-1
Gmail Midnight: 1.2.0-23+debug
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
Graphite Library: 1.0~beta1
grep: 3.1-1
gzip: 1.9-1
iCleaner Pro: 7.7.5
InspectiveC: 1.2.0
iOS Firmware: 13.2.2
iPhone Firmware (/sbin): 0-1
KSBA: 1.3.5-1
libbulletin: 0.1-153
libcolorpicker: 1.6.6
libcrashreport (SparkDev): 1.1.2
libCSColorPicker: 1.0.3
Liberty Lite (Beta): 0.2.12
libfoxfortsplash: 1.1.0
libfoxfortutils: 1.0.10-91+debug
libidn2: 6.1.2-1
libnotifications: 0.2-2
libpackageinfo (SparkDev): 1.1.4
libplist: 2.0.0-2
libSparkAppList: 1.0.3
libswift (stable): 5.0
libsymbolicate (SparkDev): 1.9.2
libtasn1: 4.13-1
libunistring: 0.9.10-1
Link Identity Editor: 2:2.1.1+elucubratus2
Locale Profiles in UTF-8: 1.0-1
LookinLoader: 1.0.5
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
Nettle: 3.4.1-1
New Curses: 5.9-1
New Curses: 6.1-1
New GNU Portable Threads: 1.6-1
NewTerm 2 (iOS 10 – 12): 2.2.1
OpenSSH: 7.9p1-3
OpenSSL 1.0 Libraries: 1.0.2s-1
p11-kit: 0.23.12-1
PortraitXI: 2.0.0-24+debug
powerlogHelperdFix: 1.0
PreferenceLoader: 2.2.4~beta1
Profile Directory: 0-1
readline: 8.0-1
RocketBootstrap: 1.0.7~beta3
sed: 4.5-1
shell-cmds: 118-8
Snappy: 1.2
Substrate Safe Mode: 0.9.6003
system-cmds: 790.30.1-2
Tape Archive: 1.30-2
TechSupport Framework (SparkDev): 1.5.2
TFDidThatSay?: 1.2.7
Translomatic: 1.3.0
TSSSaver 2: 1.0-beta-4
TweakRestrictor: 1.0.1
UIKit Tools: 1.1.15-2
unrar: 5.6.4-1
unzip: 6.0+deb9u1-1
webinspect: 0.0.1-6+debug
wget: 1.19.5-2
XZ Utils: 5.2.4-4
Zebra (BETA): 1.0~beta23-1
zip: 2.32-1
```
I have been trying to disable tweaks to find out who might be causing it but till now still not figured it out

**Comment by foxfortmobile** [comment]
@xorpix portraixi is not compatible with ios 13 anyways. remove it along with foxforttools and libfoxfortutils, you probably don't need those.

**Comment by opa334** [comment]
Same issue here! iPhone X 13.2.3, checkra1n 0.9.5, High Sierra 10.3.6 on Hackintosh.

I scrolled through Instagram and suddenly pictures stopped loading, then after a while Instagram crashed, I tried to open Cr4shed but it wouldn‘t open, then after some time SpringBoard froze up and would no longer respond to touches, after some more time the screen went black and after some more time the kernel panicked

Tweak list:

```
7-zip (POSIX): 16.02-1
AppList: 1.5.15~beta1
Apps Manager: 1.5.1-10
AppStore++: 0.9.7
APT (apt-key): 1.8.2-1
APT (libapt-pkg): 1.8.2-1
APT 0.7 Transitional (apt-key): 1:0
APT 1.4 Transitional: 1:0
APT Strict (lib): 1.8.2-1
APT: 1.8.2-3
Assuan: 2.5.1-1
Base Structure: 1-5
Berkeley DB: 6.2.32-1
BetterCCXI: 1.6.0
BigBoss Icon Set: 1.0
Bourne-Again SHell: 5.0.3-2
bzip2: 1.0.6-1
CA Certs: 0.0.2
CCModules Pro: 1.1.0
CCModules: 1.4-3
CCSupport: 1.2.2
Cephei: 1.13.1-2
Choicy: 1.0.2
CocoaTop: 2.0.2
ColorBanners 3: 1.0.0
Core Utilities (/bin): 8.31-1
Core Utilities: 8.31-1
CrashReporter (SparkDev): 1.17.2
Cydia Installer: 1.1.32~b23
Cydia Substrate: 0.9.7100~b3
Cydia Translations: 1.1.32~b1
Darwin Tools: 1.1-1
Debian Packager: 1.19.7-1
Debian Utilities: 4.8.6-1
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
Essential: 0-1
Felicity: 5.0
file: 5.35-2
Filza File Manager 64-bit: 3.7.3-16
Find Utilities: 4.6.0-2
Flame: 1.3
FLEXall: 0.0.1-11
gettext: 0.19.8-1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
grep: 3.1-1
gzip: 1.9-1
IconSupport: 1.11.1
IconSupportFix: 1.0.0
iOS Firmware: 13.2.3
iPhone Firmware (/sbin): 0-1
KSBA: 1.3.5-1
Launch Daemon Controller: 22-1
libcolorpicker: 1.6.6
libcrashreport (SparkDev): 1.1.2
libCSColorPicker: 1.0.3
libidn2: 6.1.2-1
libnotifications: 0.2-3
libpackageinfo (SparkDev): 1.1.4
libplist: 2.0.0-2
libsymbolicate (SparkDev): 1.9.2
libtasn1: 4.13-1
libunistring: 0.9.10-1
Link Identity Editor: 2:2.1.2+24497ae-1
Locale Profiles in UTF-8: 1.0-1
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
Nettle: 3.4.1-1
New Curses: 5.9-1
New Curses: 6.1-1
New GNU Portable Threads: 1.6-1
NewTerm (iOS 10 – 13): 2.3
OpenSSH: 7.9p1-3
OpenSSL 1.0 Libraries: 1.0.2s-1
p11-kit: 0.23.12-1
PreferenceLoader: 2.2.4~beta1
Profile Directory: 0-1
readline: 8.0-1
Rocket for Instagram: 3.6.6
RocketBootstrap: 1.0.7~beta3
Safari Plus: 1.7.9
sed: 4.5-1
shell-cmds: 118-8
Snapper 2: 2.2.4
Snappy: 1.3.0
SnowBoard: 1.2.74~Beta1
Stalky: 4.0.9
Substrate Safe Mode: 0.9.6003
System Info: 2.3.2-6+debug
system-cmds: 790.30.1-2
Tape Archive: 1.30-2
TechSupport Framework (SparkDev): 1.5.2
TFDidThatSay?: 1.2.7
UIKit Tools: 1.1.15-2
unrar: 5.6.4-1
unzip: 6.0+deb9u1-1
Watusi 2 for WhatsApp: 1.2.21
WatusiTools: 2.1.10
wget: 1.19.5-2
White Point Module: 1.2.1
Wraith: 0.0.3
XZ Utils: 5.2.4-4
Zenith: 1.2.2
zip: 2.32-1
```

Kernel panic: https://pastebin.com/SRN3Bxfg

**Comment by xorpix** [comment]
> @xorpix portraixi is not compatible with ios 13 anyways. remove it along with foxforttools and libfoxfortutils, you probably don't need those.

Already deleted. And btw, spotted 2.0.0 version ;) I actually disabled all of my tweaks and will see if it still occurs.

Well,  you guys seem to have kernel panic log with the same panicString as me..

**Comment by Siguza** [comment]
So out of the packages you have in common, I think only these have a real chance of being the root cause:

```
CCSupport
Cephei
Essential
RocketBootstrap
TFDidThatSay?
```

Both `Cephei` and `RocketBootstrap` state that iOS 13 is not supported. Additionally, I can't seem to find a package called `Essential` anywhere, and the same goes for `Filza File Manager 64-bit` actually (the official source doesn't say "64-bit"). Could you:

1. Try to disable the tweaks listed above and see if the issue persists?
2. Post your sources list?

**Comment by xorpix** [comment]
Here’s my sources list:

```
https://apt.bingner.com/ 
http://repo.lonestarx.net/ 
https://skitty.xyz/repo/ 
http://beta.unlimapps.com/ 
https://repo.twickd.com/ 
http://cydia.f0u4d.com/
http://rpetri.ch/repo/ 
http://repo.kritanta.me/ 
https://sparkdev.me/ 
http://apt.thebigboss.org/repofiles/cydia/ 
http://skylerk99.github.io/ 
http://cokepokes.github.io/ 
https://apt.noisyflake.com/ 
http://akusio.github.io/ 
https://revulate.dev/ 
http://cemck.github.io/repo/ 
http://dpkg9510.github.io/ 
https://soda-ldz.yourepo.com/ 
https://c1d3r.com/repo/ 
http://junesiphone.com/supersecret/ 
https://gmoran.me/repo/ 
https://zyan910.yourepo.com/ 
https://repo.rpgfarm.com/ 
http://aquawu.github.io/igg/ 
https://creaturecoding.com/repo/ 
https://repo.chariz.io/ 
https://ib-soft.net/cydia/ 
http://cydia.wuffs.org/ 
https://repo.dynastic.co/ 
http://cydia.ichitaso.com/ 
https://ib-soft.net/cydia/beta/ 
https://opa334.github.io/ 
https://chr0nict.github.io/Nepeta 
https://castyte.js.org/repo/ 
https://repo.daus.ch/ 
https://repo.pixelomer.com/ 
https://apt.alfhaily.me/ 
https://cydia.akemi.ai/ 
https://repo.linusyang.com/ 
https://calicocat.yourepo.com/ 
https://shepgoba.me/repo/ 
http://tigisoftware.com/cydia/ 
http://limneos.net/repo/ 
https://apt.geometricsoftware.se/ 
https://carbondevstudio.github.io/ 
https://skylarmccauley.xyz/hacked 
http://apt.modmyi.com/ 
https://yaypixxo.com/ 
http://julioverne.github.io/ 
https://repo.packix.com/ 
http://xenpublic.incendo.ws/ 
http://repo.incendo.ws/ 
http://cydia.kemmis.info/ 
http://cydia.zodttd.com/repo/cydia/ 
http://cydiageek.yourepo.com/ 
https://apt.arx8x.net/ 
http://getdelta.co/ 
https://nbonaparte.github.io/cydia 
https://checkra.in/assets/mobilesubstrate/
```

**Comment by xorpix** [comment]
And one more interesting thing... I can’t see Essential in Cydia..
![81F7C051-5F49-4ADD-9073-B48136A3BE94](https://user-images.githubusercontent.com/22274805/69905249-889ba280-13b9-11ea-84d1-600fedc1f204.png)

**Comment by opa334** [comment]
@Siguza 

@foxfortmobile told me in private that he has both Cephei dylibs disabled, so I don‘t think it could be the issue. I‘m the developer of CCSupport actually and would be surprised if it causes this issue as I don‘t do any stuff with processes (source code is on https://github.com/opa334/CCSupport tho). 

Filza File Manager 64-bit is a special version of Filza without the armv7 slice to save space, it is available on http://tigisoftware.com/cydia/.

Essential does not show up in Cydia for me, so I assume it is some sort of internal thing of the jailbreak maybe?

Sources list:

```
https://apt.bingner.com/
https://repo.pixelomer.com/
https://poomsmart.github.io/repo/
http://limneos.net/repo/
http://apt.thebigboss.org/repofiles/cydia/
https://opa334.github.io/
https://cokepokes.github.io/
http://system.in-appstore.com/repo/
https://lint.github.io/repo/
https://apt.fouadraheb.com/
http://apt.modmyi.com/
http://apt.golddavid.com/
https://revulate.dev/
http://tigisoftware.com/cydia/
https://chr0nict.github.io/Nepeta
https://repo.dynastic.co/
https://sparkdev.me/
http://repo.kritanta.me/
http://cydia.zodttd.com/repo/cydia/
https://dgh0st.github.io/
https://repo.chariz.io/
https://cydia.akemi.ai/
https://rpetri.ch/repo/
https://apt.alfhaily.me/
https://ib-soft.net/cydia/beta/
https://gilesgc.github.io/repo/
https://repo.packix.com/
https://apptapp.me/repo/
https://creaturecoding.com/repo/
https://apt.arx8x.net/
https://checkra.in/assets/mobilesubstrate/
```

**Comment by Siguza** [comment]
My bad, turns out `Essential` is a Cydia thing that just seems to be hidden from the Cydia UI itself.

**Comment by foxfortmobile** [comment]
As @opa334 mentioned, i had cephei disabled when i installed it since i have some trust issues with it. `TFDidThatSay` runs only in reddit and apollo app, so shouldn't cause any issue like this. Maybe its `rocketbootstrap` since it has not been updated for ios 13

**Comment by rpendleton** [comment]
For what it's worth, I think I've been seeing something similar and I don't have any invasive tweaks installed. The last occurrence I just experienced wasn't as bad as previous times, but I figured I'd document it anyway.

The last time it happened, I was in Chrome and then the app froze. I restarted the app, but it was hanging on launch for about 20 seconds. I tried to launch it again and it showed an error message about how "Some add-ons cause Chrome to crash. Please try uninstalling them." Restarting just led to a cycle between those two states.

Then I was no longer able to type in iMessage. I was able to launch Safari, but tapping the address bar would freeze Safari. I was able type type in Spotlight though, so I used that to search for something in Safari and then website content in Safari worked fine for a few minutes. Eventually, it stopped working as well.

At this point, I opened Cydia and uninstalled Rocket Bootstrap (which forced AppList and FLEXible to be uninstalled), and then did a respring. The same issue with being unable to launch Chrome persisted. I then uninstalled Frida and two tweaks I wrote that targeted specific unaffected apps, but the issue persisted.

At this point, all I had installed was Cydia Substrate and its corresponding Safe Mode. I uninstalled Cydia Substrate, and after a respring, the issues were gone and Chrome worked again.

I was unable to launch Cydia at this point to reinstall Cydia Substrate to see if that reintroduced the issue, but all of the problems I saw earlier were resolved. I tried re-installing Cydia and re-jailbreaking and re-installing Cydia, but neither approach allowed me to launch it. Deleting a metadata file fixed that issue though. I've reinstalled Cydia Substrate and the two tweaks I wrote that target specific apps (just patching jailbreak detection), so I'll see if the issue occurs over a few days now that I don't have Rocket Bootstrap or FLEXible installed.

Is there a specific location I can look for logs that might be of assistance? I'm taking a sysdiagnose in case they'll be in there, but I'm not sure what logs are actually useful for debugging this type of issue. I was unable to find crash reports for any of the affected apps in the Analytics Data section of Settings.

**Comment by opa334** [comment]
I just had this issue again. Happened while browsing Safari this time. I have removed tfdidthatsay since then so we can rule that out too.

There were some similar issues with Substrate before (https://github.com/pwn20wndstuff/Undecimus/issues/165), so maybe it is a new bug with it in iOS 13? That or rocketbootstrap is at fault here, I can't test it however cause this is a daily driver and I rely on some tweaks that depend on rocketbootstrap.

**Comment by xorpix** [comment]
I’m still testing it. Haven’t had reboot yet since updating to checkra1n 0.9.6... But will see.. Usually, it appears on 4th-6th day after jailbreaking.

**Comment by xorpix** [comment]
https://reddit.com/r/jailbreak/comments/e6473e/discussion_cydia_substrate_dissables_itself/

It appears that all those problems are connected to Cydia Substrate.

**Comment by xorpix** [comment]
It’s just happened again to me. The panicString in the log is the same:
https://we.tl/t-Ngr3ZIZQVR

**Comment by xorpix** [comment]
I opened Cydia and refreshing sources froze (the wheel was still spinning tho)

**Comment by foxfortmobile** [comment]
Update: 
I have removed `Eclipse Dark Mode (iOS 12)` and have not got the issue again in the past few days. Will keep monitoring.

**Comment by xorpix** [comment]
An update which I already wrote in discord.

Substrate just stopped working again. Some tweaks stopped working and after I did respring the rest of tweaks stopped working completely. After that I did ldrestart and the phone went into dimmed respring wheel until rebooted unjailbroken. 

I was told that devs are already working on a fix.

**Comment by youngslim** [comment]
[#652 ](https://github.com/checkra1n/BugTracker/issues/652) was my issue, I have both Cephei and RocketBootstrap installed, But the different thing is I never got freeze when I use my phone like you guys did, It only got into respring loop and reboot when I unlock it or when phone is idle, It just suddenly starts respring and for a couple minutes, It reboots. Very curious why it never got me into safe mode, thought it was supposed to deal with this

**Comment by opa334** [comment]
After doing a DFU restore to 13.3 (I restored an iTunes backup and all tweaks using batchomatic afterwards, so the setup is exactly the same), I'm no longer getting this issue.

**Comment by xorpix** [comment]
I've installed Crash Reporter by Spark. Maybe it will catch something useful. Keeping investigation of this issue.

**Comment by Siguza** [comment]
At this point I'm fairly confident that this, along with a range of other issues, is caused by Substrate crashing.

**Comment by xorpix** [comment]
So it needs fix by Saurik?

**Comment by Siguza** [comment]
Yes. But I also know that he doesn't have much spare time at the moment, and this seems like an issue that might take multiple days, if not weeks, to debug. :/

**Comment by xorpix** [comment]
Moreover, as i remember he said earlier that he is not interested in maintaining it anymore. I really hope that he will actually do this and will wait for it..

**Comment by xorpix** [comment]
And also wait for a dongle/arduino battery case solution i guess.. Because when it happens while i don't have the access to a computer, i'm stuck unjailbroken. And this is what sucks the most about it.

**Comment by foxfortmobile** [comment]
I updated my phone to 13.3 yesterday and jailbroken using checkrain 0.9.7. When using it to edit a photo, it randomly started to lag, then froze and eventually that spinning wheel appeared and stay for 2 minutes. Then the device rebooted.
Sadly my CrashReporter itself is crashing and not opening anymore. So can't check any logs from there.

On the other side, there is a user who claims to get this issue more often when using portraitxi to take a picture.  He said randomly when he would take pictures, the phone would freeze and reboot. He says this log is closest to the time it happened:
https://pastebin.com/WAwHbKnV

Note: PortraitXI is only injected in camera process. So im not sure how it could cause other process to hang too.

**Comment by vladaad** [comment]
I have the same issue, and have a few crashlogs including a kernel panic.
I also have this issue only while using PortraitXI and taking multiple portrait photos and editing them. This however should only be causing the springboard to crash at most and not a kernel panic.
I've spoken with foxfortmobile since it's his tweak and it seems as though it's not PortraitXI's fault.
Crash logs:

Kernel panic log: https://pastebin.com/VWGy8fuS
stacks+backboardd crashlog 1: https://pastebin.com/sTyZx3Au
stacks+backboardd crashlog 2: https://pastebin.com/7UNnFagB
stacks+thermalmonitord crashlog: https://pastebin.com/JjXwzbWF

Not sure if the "stacks+..." crashlogs are useful but I included them anyway

**Comment by xorpix** [comment]
Substrate has just unloaded itself after almost 6 days of uptime, but I’ve successfully got it back to work using NewTerm (su; /etc/rc.d/substrate; killall SpringBoard). Luckily, I’ve got no freezes yet.

Unfortunately, CrashReporter hasn’t caught Substrate’s fail.

**Comment by xorpix** [comment]
Well, it just hang the device again. Everything became slow and laggy until it completely froze. So there are always two scenarios in my case. Unload or freezing. The last one is worse tho.

Will boot back into jailbroken and see if CrashReporter caught something.

**Comment by xorpix** [comment]
So, CrashReporter didn’t catch anything. I guess its process hang with the whole system, so it was unable to do it

**Comment by foxfortmobile** [comment]
@Siguza I was using my ip X to develop ios apps and was running some hardcore computer graphics algorithm which take around 1.5gb of memory. Then the app started lagging, so i killed it in xcode. Then i launched Filza and it got stuck on black screen. Tried using my CC respring toggle and the device froze. I encountered the same exact issue during app dev some days ago.

As @vladaad pointed out, he gets it often from portraitxi which uses big neural networks and can consume around 800Mb-1.2Gb of ram, this could explain why he gets it after taking some images. 

To me, the app should just crash if it is taking too much memory and should not cause substrate to hang and eventually reboot the device.

My technical details:
Iphone X
ios 13.3
Checkra1n 0.9.7

**Comment by xorpix** [comment]
So, Substrate got the update today. Let’s see if it fixes those issues.

**Comment by vladaad** [comment]
I actually think it did. I took like 5-6 portraits with PortraitXI and so far my phone hasn't crashed. Still, further testing if it fixed the issue is needed.
@foxfortmobile maybe try that running that algorithm that takes up 1.5gb ram again just to check if it's fixed with the new substrate update?

**Comment by xorpix** [comment]
No, unfortunately it didn’t fix it. My device has just started hanging while refreshing sources in Cydia. I tried to install some tweak, but installation screen froze. Then I reached CC for manual respring and when I pressed the button, the phone froze completely. After that standard scenario (dimmed respring wheel and so on).

**Comment by youngslim** [comment]
Yeah, I still have that suddenly respring loop and then reboot problem, turns out it never survive more than 3 days, So now I have to re-jailbreak every two days. But checkra1n is still the stablest jb during the 2 days, smooth and fast.

By the way, I don't know why my issue been mentioned into this one, I never had that **tweaks stop working** problem, or **freeze after 1 week** problem, since my phone never reached that long time, it always randomly reboots after 2 days, never reached the third day.

sorry my english is so fk poor.

**Comment by xorpix** [comment]
In my current case, it happened only after 1 day and 21 hours of uptime. So, it seems that it even got worse, idk..

**Comment by youngslim** [comment]
> In my current case, it happened only after 1 day and 21 hours of uptime. So, it seems that it even got worse, idk..

yeah, exactly, just 1 day and about 20-24 hours, maybe it will reached to 2 days and a few hours, the reboot happens, cause we can't just stay looking at the uptime, only the about time.

looks like we got the same problem :(

**Comment by xorpix** [comment]
Everything of this is one problem. It’s related to the issue with Substrate. Hopefully, Saurik will begin investigation of this soon.

**Comment by youngslim** [comment]
I saw some posts on reddit about this issue, not everyone, just a small group of people have this problem. it's fine, we can just re-jailbreak everyday, stupid solution.

**Comment by xorpix** [comment]
No, it’s a terrible solution (and honestly not a solution at all), because I don’t have access to my Mac 24/7. And usually it happens, when I don’t have Mac near, so I remain unjailbroken.

**Comment by youngslim** [comment]
I know, it sucks, I got a machintosh working so everytime before I go out I do a re-jailbreak. it's the only way before we got windows version.....

**Comment by foxfortmobile** [comment]
i can confirm that this new substrate update did not solve the problem. Was running my app and it hit 1.4gb of RAM, i stopped, made some changes and relaunched via XCode but the app did not re launch. So i swiped down and hit respring cc toggle and whole phone froze. Had to rejailbreak. Apparently high memory usage makes substrate go crazy.

**Comment by xorpix** [comment]
Substrate has just received the update which should fix all issues related to unloading or freezing. According to Sam, it was happening “due to a mach port name leak that would cause it to no longer be able to modify processes after spawning somewhere around 50,000 processes”. So I hope it actually got fixed.

**Comment by StateOfInstinct** [comment]
I did update substrate and this still happened yesterday

**Comment by xorpix** [comment]
It hasn’t crashed for me yet. I’ll write here if it actually crashes

**Comment by rpendleton** [comment]
I also updated Substrate but still experienced the same freezing and eventual restart crash today. Is there some kind of log on my device that can help?

**Comment by GlacierIsland** [comment]
My device (iPad 6) also crashes and reboots. For me, it mainly seems to occur under load, such as mobile gaming + multitasking.

**Comment by xorpix** [comment]
So, my device is still up. Seems, the issue is gone for me.

**Comment by xorpix** [comment]
You guys better check your tweaks. Some of them might be bad.

**Comment by foxfortmobile** [comment]
@xorpix it does not necessarily need to be tweaks but instead it happens when you have high memory usage. Like i mentioned previously, i often get it when the app i run hits around 1.2-1.4gb of ram. this makes substrate go crazy and freeze

**Comment by xorpix** [comment]
But now I have like 37 tweaks. Some of them are “heavy”. And after installing the update I haven’t  got a freeze or unloading. So it seems that it fixed the issue for me.

**Comment by Shadowgar** [comment]
I’ve updated substrate and settings, messages, phone, contacts, any browser use just freezes until reboot. Restored/rejailbreak works for a few hours and freezes again. No other tweaks installed but jailbreaking. Is this the same issue everyone else is having?

**Comment by youngslim** [comment]
Guys, I've already have 11 days of uptime, looks like my problem is gone.
Before substrate got updated, I uninstalled a tweak which I think it's ralated to the reboot, and got 4 days of uptime, by now it's 11.

**Comment by StateOfInstinct** [comment]
> I’ve updated substrate and settings, messages, phone, contacts, any browser use just freezes until reboot. Restored/rejailbreak works for a few hours and freezes again. No other tweaks installed but jailbreaking. Is this the same issue everyone else is having?

Pretty much. I just crashed again.

**Comment by xorpix** [comment]
So, it’s passed ~10 days since I updated the Substrate and I had no a single freeze or unloading since then. The issue may be considered resolved for me.

**Comment by xorpix** [comment]
@Siguza i don’t know if to close the issue or not. I think that people above that have some problems with their jailbreaks are dealing with that not because of Substrate anymore. Imo

**Comment by vladaad** [comment]
This issue should be re-opened - even with latest substrate this still happens.
Crashlog: https://pastebin.com/78QHSg0N

**Comment by ahammouri** [comment]
@Siguza  i'm on the latest substrate update but my phone still freezes, i cant get more than 2 days of uptime

**Comment by trantuan2** [comment]
I used portrailxl on iphone7 ios 13.2.3 after I used it to take photos, my iphone was rebooted and the jailbreak was lost

**Comment by HaGii** [comment]
For me the error still occurs and the newest update of Cydia substrate didn’t resolve the issue.
I also tried to find some people, who may have the same issue on reddit and it seems like there are people who still have those freezes and reboots. 
So is it possible to reopen the issue?

**Comment by gnlc** [comment]
iPhone X (GSM [A1901]), iOS 13.3.1, checkra1n 0.9.8

Peek-a-View is perfect for demonstrating this problem. Just swipe pictures multiple times and app crashes for using too much memory.
Without Jailbreak or with jailbreak and not having Cydia Substrate (0.9.7101) app crashes and it can be opened normally and crash and repeat and iPhone is working normally.

Install Substrate (0.9.7101), respring and using Peek-a-View and after first crash iPhone won't work properly and will slowly force reboot.
I have tried this multiple times and crash-reboot is 100% with Peek-a-View and Substrate.

**Comment by Siguza** [comment]
Reopening this, I guess.

**Comment by jacobcxdev** [comment]
I have an iPad 7th Generation which will randomly panic noticeably often. At present, it can take as little as 15 minutes to panic.

My panic logs are attached below:
* [panic-full-2020-02-21-172316.txt](https://github.com/checkra1n/BugTracker/files/4262093/panic-full-2020-02-21-172316.txt)
* [panic-full-2020-02-21-183333.txt](https://github.com/checkra1n/BugTracker/files/4262094/panic-full-2020-02-21-183333.txt)
* [panic-full-2020-02-21-204645.txt](https://github.com/checkra1n/BugTracker/files/4262095/panic-full-2020-02-21-204645.txt)
* [panic-full-2020-02-21-205757.822.txt](https://github.com/checkra1n/BugTracker/files/4262096/panic-full-2020-02-21-205757.822.txt)
* [panic-full-2020-02-21-232358.txt](https://github.com/checkra1n/BugTracker/files/4262097/panic-full-2020-02-21-232358.txt)
* [panic-full-2020-02-24-212726.txt](https://github.com/checkra1n/BugTracker/files/4262098/panic-full-2020-02-24-212726.txt)
* [panic-full-2020-02-26-203033.txt](https://github.com/checkra1n/BugTracker/files/4262099/panic-full-2020-02-26-203033.txt)
* [panic-full-2020-02-27-012400.883.txt](https://github.com/checkra1n/BugTracker/files/4262100/panic-full-2020-02-27-012400.883.txt)
* [panic-full-2020-02-27-122602.txt](https://github.com/checkra1n/BugTracker/files/4262101/panic-full-2020-02-27-122602.txt)
* [panic-full-2020-02-27-130545.991.txt](https://github.com/checkra1n/BugTracker/files/4262102/panic-full-2020-02-27-130545.991.txt)
* [panic-full-2020-02-27-134944.txt](https://github.com/checkra1n/BugTracker/files/4262103/panic-full-2020-02-27-134944.txt)
* [panic-full-2020-02-27-140411.txt](https://github.com/checkra1n/BugTracker/files/4262104/panic-full-2020-02-27-140411.txt)

*NB: The final few panics are **definitely** random, whereas some of the first panics may be due to a tweak I’ve been working on for mediaserverd.*

**Comment by jacobcxdev** [comment]
I have an iPad 7th Generation which will randomly panic noticeably often. At present, it can take as little as 15 minutes to panic.

My panic logs are attached below:
* [panic-full-2020-02-21-172316.txt](https://github.com/checkra1n/BugTracker/files/4262093/panic-full-2020-02-21-172316.txt)
* [panic-full-2020-02-21-183333.txt](https://github.com/checkra1n/BugTracker/files/4262094/panic-full-2020-02-21-183333.txt)
* [panic-full-2020-02-21-204645.txt](https://github.com/checkra1n/BugTracker/files/4262095/panic-full-2020-02-21-204645.txt)
* [panic-full-2020-02-21-205757.822.txt](https://github.com/checkra1n/BugTracker/files/4262096/panic-full-2020-02-21-205757.822.txt)
* [panic-full-2020-02-21-232358.txt](https://github.com/checkra1n/BugTracker/files/4262097/panic-full-2020-02-21-232358.txt)
* [panic-full-2020-02-24-212726.txt](https://github.com/checkra1n/BugTracker/files/4262098/panic-full-2020-02-24-212726.txt)
* [panic-full-2020-02-26-203033.txt](https://github.com/checkra1n/BugTracker/files/4262099/panic-full-2020-02-26-203033.txt)
* [panic-full-2020-02-27-012400.883.txt](https://github.com/checkra1n/BugTracker/files/4262100/panic-full-2020-02-27-012400.883.txt)
* [panic-full-2020-02-27-122602.txt](https://github.com/checkra1n/BugTracker/files/4262101/panic-full-2020-02-27-122602.txt)
* [panic-full-2020-02-27-130545.991.txt](https://github.com/checkra1n/BugTracker/files/4262102/panic-full-2020-02-27-130545.991.txt)
* [panic-full-2020-02-27-134944.txt](https://github.com/checkra1n/BugTracker/files/4262103/panic-full-2020-02-27-134944.txt)
* [panic-full-2020-02-27-140411.txt](https://github.com/checkra1n/BugTracker/files/4262104/panic-full-2020-02-27-140411.txt)

**Comment by opa334** [comment]
This panic happens when an application allocates a lot of memory. There was a memory management problem in Safari Plus and a user was able to replicate this panic every time (my code sucked and in some instances tried to allocate multiple gigabytes of RAM when merging a movpkg directory into a ts file). After rewriting the merging code to use less memory, the panic stopped. It might be possible to create an application that replicates this, I will try it soon.

**Comment by QcSamuel** [comment]
[panic-full-2020-03-01-112857.txt](https://github.com/checkra1n/BugTracker/files/4272135/panic-full-2020-03-01-112857.txt)
iphone 7 ios 13.3.1
checkra1n 0.9.8

**Comment by RexSonic** [comment]
[Panic log ](https://pastebin.com/4F4abdc4) 
iPhone 8 iOS 13.3.1
Checkra1n 0.9.8

**Comment by QcSamuel** [comment]
https://github.com/checkra1n/BugTracker/issues/1089

**Comment by QcSamuel** [comment]
https://github.com/checkra1n/BugTracker/issues/1089

**Comment by QcSamuel** [comment]
another crash log on 0.9.8.2
[2020-03-31.txt](https://github.com/checkra1n/BugTracker/files/4424276/2020-03-31.txt)

**Comment by j0hnlam** [comment]
Panic log: https://we.tl/t-ngPwDhYPNY

After charging overnight then using the phone to check notifications for 2 min.
Apps wouldn’t respond further then black screen with spinning wheel and phone reboots with no jailbreak.

**Comment by QcSamuel** [comment]
another panic log:https://we.tl/t-8CDTdlEJml
also any update on this issue ? it's really annoying because it's random

sorry if this question sound a little rude

**Comment by QcSamuel** [comment]
new workaround for the ios 13 jetslam issue will install it and use my phone for a while to see if the crashing stop with this https://github.com/hbang/StopCrashingPls
edit: it's on the chariz repo btw

**Comment by ahammouri** [comment]
Can you keep us updated please ? And use heavy ram usage apps please ? @QcSamuel

**Comment by QcSamuel** [comment]
@ahammouri sure :)

**Comment by QcSamuel** [comment]
with StopCrashingPls the crash is still there oof
https://we.tl/t-v21g7BusFU

**Comment by ahammouri** [comment]
@QcSamuel 

What about this one ? 
https://www.reddit.com/r/jailbreak/comments/g8fzw0/release_fix_random_freezes_and_resprings_deb/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

I’m not currently jailbroken else i would have tested it myself so thank you for testing it :)

**Comment by QcSamuel** [comment]
@ahammouri will rejailbreak and i will try that fix and report back the result :)

**Comment by StateOfInstinct** [comment]
Im going to try it out too and I’ll report back in a week or two

**Comment by Ntwadum3la** [comment]
I have tried StopCrashingPls and the ‘random freezes and respring fix .deb’ but the crash still occurs on the exact same way: Slowly freezing > respring wheel > reboot.

**Comment by StateOfInstinct** [comment]
> I have tried StopCrashingPls and the ‘random freezes and respring fix .deb’ but the crash still occurs on the exact same way: Slowly freezing > respring wheel > reboot.

same with me. I did last for a very long time with both installed.

**Comment by QcSamuel** [comment]
random freeze fix and stopcrashingpls didnt fix anything now with them my phone reboots after 2 days before it was one week

edit: maybe substrate need another update to fix that ?

**Comment by QcSamuel** [comment]
https://github.com/checkra1n/BugTracker/issues/1317

**Comment by smailpouri** [comment]
same problem iPhone7 ios 13.4.1. Though the StopCrashPls did help a bit. I can get away with a few days of no crash sometimes. Sometimes not.

**Comment by moteshubham** [comment]
I have same issue with my **iPhone X, iOS 13.4.1**, that _all of apps freeze and after 3-4 minutes, device freezes followed by complete respring_, and back to normal happening daily. researched a lot, but no solution yet.

**Comment by Mikagreat** [comment]
[iPhone 7 iOS 13.3.1/13.4/13.4.5] The OS always freezed cause of userspace watchdog timeout.  #1208

**Comment by fennectech** [comment]
ipad pro with 0.10.1 checkra1n and ios 13.4   Apps hang    but ui remains functional   Attempting to switch apps or run a respring with ccsupport button causes the ui to hang   Locking screen and unlocking  UI remains hanged   device doesnt lock   After 3 or 4 minutes of this  The device attempts to respring and sits on the spinner for a minute or two   Then the apple logo appears and the device reboots happy as a clam    (but unjailbroken)    SSH does not respond when its trying to respring but the device does repond to pings

**Comment by moteshubham** [comment]
**Finally I found the Fix**
I spent a lot of time searching for the solution and finally I found it.
Check this reddit post, I tried it and it has been 25 days I did not experienced random freeze.
https://www.reddit.com/r/jailbreak/comments/g8fzw0/release_fix_random_freezes_and_resprings_deb/

**Fixed**

**Comment by Ntwadum3la** [comment]
> **Finally I found the Fix**
> I spent a lot of time searching for the solution and finally I found it.
> Check this reddit post, I tried it and it has been 25 days I did not experienced random freeze.
> https://www.reddit.com/r/jailbreak/comments/g8fzw0/release_fix_random_freezes_and_resprings_deb/
> 
> **Fixed**

Does not work for me. I switched to unc0ver. Maybe this will fix it for me.

**Comment by opa334** [comment]
@mo

> **Finally I found the Fix**
> I spent a lot of time searching for the solution and finally I found it.
> Check this reddit post, I tried it and it has been 25 days I did not experienced random freeze.
> https://www.reddit.com/r/jailbreak/comments/g8fzw0/release_fix_random_freezes_and_resprings_deb/
> 
> **Fixed**

That package fixes an entirely unrelated issue that causes random resprings. This issue here however causes a kernel panic and won't be fixed by that package.

**Comment by QcSamuel** [comment]
i'm now using chimera1n (replace substrate with substitue) no longer having springboard stutter will see if the kernel panic is still there with that

**Comment by StateOfInstinct** [comment]
> i'm now using chimera1n (replace substrate with substitue) no longer having springboard stutter will see if the kernel panic is still there with that

Same. It’s been really good for me.

**Comment by ahammouri** [comment]
Is there a guide to install chimera1n

**Comment by QcSamuel** [comment]
> Is there a guide to install chimera1n
before doing rootfs backup everything with batchomatic then follow this https://www.reddit.com/r/jailbreak/comments/g6g2jk/tutorial_the_simple_unofficial_guide_to/?

**Comment by jayguar1206** [comment]
> i'm now using chimera1n (replace substrate with substitue) no longer having springboard stutter will see if the kernel panic is still there with that

Can confirm chimera1n fixed the issue with substitute. No more random respring/reboots and kernel panics. My current uptime right now is 15 days and still going

**Comment by ahammouri** [comment]
> Is there a guide to install chimera1n
> before doing rootfs backup everything with batchomatic then follow this https://www.reddit.com/r/jailbreak/comments/g6g2jk/tutorial_the_simple_unofficial_guide_to/?

Will all tweaks work with chimera1n ? also do i have to run the script everytime I jailbreak ?

**Comment by StateOfInstinct** [comment]
> > Is there a guide to install chimera1n
> > before doing rootfs backup everything with batchomatic then follow this https://www.reddit.com/r/jailbreak/comments/g6g2jk/tutorial_the_simple_unofficial_guide_to/?
> 
> Will all tweaks work with chimera1n ? also do i have to run the script everytime I jailbreak ?

Yeah all tweaks that work with chimera1n. No you don’t have to run the script everytime. I just updated to the newest checkra1n and rejailbreak. Everything was still there

**Comment by daspri** [comment]
Would the substitute from uncover work?  Is there any way to switch to that in cydia?

This bug is a continuing pain, but I'd prefer not to have to install sileo, I just want checkra1n to work reliably for a long uptime.

**Comment by Ntwadum3la** [comment]
> Would the substitute from uncover work? Is there any way to switch to that in cydia?
> 
> This bug is a continuing pain, but I'd prefer not to have to install sileo, I just want checkra1n to work reliably for a long uptime.

You can jailbreak with Unc0ver and it will install substitute. Crash is gone.

**Comment by daspri** [comment]
> You can jailbreak with Unc0ver and it will install substitute. Crash is gone.

For now, but that doesn't fix future versions after Apple fixes the bug used by Unc0ver.

**Comment by StateOfInstinct** [comment]
> Would the substitute from uncover work? Is there any way to switch to that in cydia?
> 
> This bug is a continuing pain, but I'd prefer not to have to install sileo, I just want checkra1n to work reliably for a long uptime.

Just install cydia back and hide Sileo

**Comment by daspri** [comment]
> Just install cydia back and hide Sileo

After reading the above tutorial I just think there has to be an easier way (ie: 1 click!) to switch between substrate and substitute on a checkra1n device, especially if the bug in substrate can't be fixed.

**Comment by saurik** [comment]
So, I only just today ran across a link to this issue. (No one had tagged me in it or anything, and Sam hadn't told me that anything wasn't working for anyone, even when I talk to him about Substrate in depth... like I did a few times this past week ;P.) I don't know if anyone even still cares (and if not, that's more than OK), but I guess I'll spend some time trying to play with "if an app uses a ridiculous amount of memory, that can break substrate" and see if I can replicate the failure. (If not, I can try to come up with some kind of logs that would be useful, but that is way more difficult than it sounds.)

**Comment by xorpix** [comment]
@saurik 
Hello! Thank You for paying attention to this problem.
This issue seems to be pretty weird. It was occurring for me when I was using unc0ver when it was using Substrate, then it was occurring when I used checkra1n. And after some update (I don’t remember what exactly) my device actually stopped freezing. But there was an app from App Store which had issues with using of memory. Called Peek-a-View. When I scrolled the photos in the app so fast, my device rebooted. The same actions on jailbreak with Substitute was leading just to that app crashing. Also @foxfortmobile mentioned he triggered Substrate memory issue with his tweaks which use a lot of memory because of heavy algorithms used in them. And some other people report they have the exact same issue I used to have.

**Comment by foxfortmobile** [comment]
> Also @foxfortmobile mentioned he triggered Substrate memory issue with his tweaks which use a lot of memory because of heavy algorithms used in them

This happens in PortraitXI because it use computationally expensive methods like running big neural networks via CoreML and processes full resolution images.

@saurik Just to clear out any confusion, this has nothing to do with tweaks (unlike to what others are believing). I can reproduce this issue by making a simple app that deals with big images by applying filters to them (without having any tweaks). Note that the same app runs perfectly in stock mode. From my observations, it seems that if the process has peaks to over 600Mb of memory, substrate tends to freeze and reboots.

**Comment by saurik** [comment]
I believe this bug has been fixed in 0.9.7104 (which I've sent to @sbingner to release, assuming it doesn't catastrophically fail or something). While I managed to replicate the issue with memory pressure, and used that to verify the bug seemed fixed, it turns out a really simple replication was just "killall -9 substrated": when my page cache daemon came back online it would fail to re-request mach port no senders notifications due to what frankly seems like a bug in the API (if it isn't, then the API isn't both poorly documented and makes no sense...) that I was able to come up with a workaround for :/.

**Comment by xorpix** [comment]
@saurik I remembered that there also was one more bug. One day I wanted to remove all my tweaks and I did it via removing Cydia Substrate using Cydia. But after that Cydia stopped opening. Like... I tried all suggested solutions. Clearing all traces of Cydia, removing metadata file, installing Substrate again, even restoring rootFS. Nothing helped much. Cydia remained broken. Only a clean restore helped.

**Comment by saurik** [comment]
> One day I wanted to remove all my tweaks and I did it via removing Cydia Substrate using Cydia. But after that Cydia stopped opening.

FWIW, I just tried this on checkra1n with the pending 0.9.7104, and it worked. I would have been surprised that that behavior ever would have been a problem, though (and I do feel like @sbingner would have told me if something didn't work that extremely...).

> Like... I tried all suggested solutions. Clearing all traces of Cydia, removing metadata file, installing Substrate again, even restoring rootFS. Nothing helped much. Cydia remained broken. Only a clean restore helped.

This is just brutal, though... like, I don't even understand how this would be possible, as I don't think you need Substrate installed at all on checkra1n for everything to work correctly... and installing / uninstalling Substrate doesn't edit any key files like it used to a decade ago.

**Comment by xorpix** [comment]
Well, it’s possible that it could be some other tweak which was removed with Cydia Substrate.

**Comment by foxfortmobile** [comment]
I updated substrate to v0.9.7104 and ran some expensive image manipulation algorithm making the memory peak at 1.1GB. I confirm that this update solves the issue and my device did not freeze/reboot. @saurik Thanks for the quick update.

**Comment by xorpix** [comment]
My friend who’s on checkra1n said that issue is gone for him too. So I guess it’s pretty much fixed. Thank You @saurik !

**Comment by NAIFs21** [comment]
https://ib-soft.net/cydia/beta
